services:
  - type: web
    name: ecommerce-django
    env: docker
    plan: free
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: 01^wf!ifn3tn&p!bqsk54s_uws3(@_vc@kxr+oo((%ugrti_mr
      - key: ALLOWED_HOSTS
        value: ecommerce-django-11y3.onrender.com
      - key: DATABASE_URL
        fromDatabase: 
          name: ecommerce-db
          property: connectionString

databases:
  - name: ecommerce-db
    plan: free
