# Generated by Django 5.2.1 on 2025-05-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='User_log',
        ),
    ]
