# Generated by Django 5.2.1 on 2025-05-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_user_log_order_userlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Userlog',
            new_name='user',
        ),
    ]
